apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-apps
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated: {}

  source:
    repoURL: https://github.com/nielstenboom/argocd-demo.git
    targetRevision: master
    path: charts/platform-apps
    helm:
      valueFiles:
      - values.yaml