## Fill in common variables here
environment: dev
repoURL: https://github.com/nielstenboom/argocd-demo.git
targetRevision: master


# enable more of them on better hardware
prometheus:
  enabled: false

ingress_nginx:
  enabled: false

fluentd:
  enabled: false

redis:
  enabled: true

postgresql:
  enabled: true