{{ if .Values.fluentd.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentd
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
    
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: charts/fluentd
    # helm:
    #   valueFiles:
    #   - values.yaml
{{ end }}