{{ if .Values.ingress-nginx.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
    
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

  source:
    repoURL: https://github.com/nielstenboom/argocd-demo.git
    targetRevision: master
    path: charts/ingress-nginx
    # helm:
    #   valueFiles:
    #   - values.yaml
{{ end }}
