apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
    
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

  source:
    repoURL: https://github.com/nielstenboom/argocd-demo.git
    targetRevision: master
    path: charts/postgresql
    # helm:
    #   valueFiles:
    #   - values.yaml